name: Build

on:
  pull_request:
  push:
    branches: ['**']

jobs:
  nextflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: MillironX/setup-nextflow@v1
      # first validate flow - uses stub blocks
      - run: nextflow run main.nf -stub-run -profile test
      # then run with test data - uses script/shell/exec blocks
      - run: example/prepare_test_data.sh
      # stub run first - standard
      - run: nextflow -c nextflow.stubRun.config run main.nf -profile test -stub-run
      # stub run first - augment
      - run: nextflow -c nextflow.stubRun.config run main.nf -profile test -stub-run --augment --repeats $PWD/test_data/repeats.txt --multistr $PWD/test_data/multi_str.txt
      # real exec as it works
      - run: nextflow run main.nf -profile test
      - run: nextflow run main.nf -profile test --augment --repeats $PWD/test_data/repeats.txt --multistr $PWD/test_data/multi_str.txt
